describe('Payment Process', () => {
    it('As a user I can select payment method', () => {
      cy.visit('https://www.sepulsa.com/transaction/checkout')
      cy.visit('https://www.sepulsa.com/signin')
      cy.get('input[name="email"]').type('putrimanda985@gmail.com')
      cy.get('input[name="password"]').type('220703Amanda_')
      cy.contains('Masuk').click()
      cy.location('host').should('eq', 'www.sepulsa.com')
      cy.wait(5000)
      cy.contains('Lainnya').click()
      cy.url().should('include', '/menu')
      cy.contains('p', 'Telekomunikasi').scrollIntoView().click() 
      cy.get('#product_type_0').click()
      cy.url().should('eq', 'https://www.sepulsa.com/transaction/pulsa')
      cy.get('input[name="phone_number"]').type('08214439272')
      cy.get('.nominal-item').should('be.visible')
      cy.get('[id="Telkomsel Rp5.000"]').click()
      cy.url().should('eq', 'https://www.sepulsa.com/transaction/checkout')
      cy.get('#section-list-payment').should('be.visible')
      cy.get('#section-list-payment').first().click()
      cy.get('#submit_payment').click()
    })

    it('As a user I can use a promotional code', () => {
      cy.visit('https://www.sepulsa.com/transaction/checkout')
      cy.visit('https://www.sepulsa.com/signin')   
      cy.get('input[name="email"]').type('putrimanda985@gmail.com')
      cy.get('input[name="password"]').type('220703Amanda_')  
      cy.contains('Masuk').click()
      cy.location('host').should('eq', 'www.sepulsa.com') 
      cy.contains('Lainnya').click()
      cy.url().should('include', '/menu')
      cy.contains('p', 'Telekomunikasi').scrollIntoView().click() 
      cy.get('#product_type_0').click()
      cy.url().should('eq', 'https://www.sepulsa.com/transaction/pulsa')
      cy.get('input[name="phone_number"]').type('08214439272')
      cy.get('.nominal-item').should('be.visible')
      cy.get('[id="Telkomsel Rp5.000"]').click()
      cy.url().should('eq', 'https://www.sepulsa.com/transaction/checkout')
      cy.contains('#panel_promotion', 'Apakah kamu punya kode promosi?').click()
      cy.get('#promotion_code').should('be.visible')
      cy.get('#promotion_code').type('YOUR_PROMO_CODE')
      cy.get('#section-list-payment').should('be.visible')
      cy.get('#section-list-payment').first().click()
      cy.get('#submit_payment').click()
    })
  
    it('As a user I cannot pay if I do not select a payment type', () => {
      cy.visit('https://www.sepulsa.com/transaction/checkout')
      cy.visit('https://www.sepulsa.com/signin')
      cy.get('input[name="email"]').type('putrimanda985@gmail.com')
      cy.get('input[name="password"]').type('220703Amanda_')
      cy.contains('Masuk').click()
      cy.location('host').should('eq', 'www.sepulsa.com')
      cy.contains('Lainnya').click()
      cy.url().should('include', '/menu')
      cy.contains('p', 'Telekomunikasi').scrollIntoView().click() 
      cy.get('#product_type_0').click()
      cy.url().should('eq', 'https://www.sepulsa.com/transaction/pulsa')
      cy.get('input[name="phone_number"]').type('08214439272')
      cy.get('.nominal-item').should('be.visible')
      cy.get('[id="Telkomsel Rp5.000"]').click()
      cy.url().should('eq', 'https://www.sepulsa.com/transaction/checkout')
      cy.get('#submit_payment').click()
      cy.get('#error_select_payment').should('be.visible').and('contain', 'Kamu belum memilih metode pembayaran')
    })
  })